// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SakuraFilter.Infrastructure.Data;

#nullable disable

namespace SakuraFilter.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260717125735_AddMr1PrimaryKeyAndV2Fields")]
    partial class AddMr1PrimaryKeyAndV2Fields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SakuraFilter.Core.Entities.AlertHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("channel");

                    b.Property<JsonDocument>("ContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content_json");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<JsonDocument>("Recipients")
                        .HasColumnType("jsonb")
                        .HasColumnName("recipients");

                    b.Property<string>("Response")
                        .HasColumnType("text")
                        .HasColumnName("response");

                    b.Property<DateTimeOffset>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_alert_history");

                    b.ToTable("alert_history", (string)null);
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.AlertRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<JsonDocument>("Channels")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("channels");

                    b.Property<JsonDocument>("Conditions")
                        .HasColumnType("jsonb")
                        .HasColumnName("conditions");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<JsonDocument>("Recipients")
                        .HasColumnType("jsonb")
                        .HasColumnName("recipients");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_alert_rules");

                    b.HasIndex("Type")
                        .IsUnique()
                        .HasDatabaseName("ix_alert_rules_type");

                    b.ToTable("alert_rules", (string)null);
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.CrossReference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDiscontinued")
                        .HasColumnType("boolean")
                        .HasColumnName("is_discontinued");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_published");

                    b.Property<string>("MachineType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("others")
                        .HasColumnName("machine_type");

                    b.Property<string>("Oem2")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("oem_2");

                    b.Property<string>("OemBrand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("oem_brand");

                    b.Property<string>("OemNo3")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("oem_no_3");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName1")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("product_name_1");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_cross_references");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_cross_references_product_id");

                    b.HasIndex("OemBrand", "OemNo3")
                        .IsUnique()
                        .HasDatabaseName("uq_xrefs_brand_oem3")
                        .HasFilter("is_discontinued = false");

                    b.HasIndex("OemBrand", "SortOrder", "OemNo3")
                        .HasDatabaseName("idx_xrefs_brand_oem3_sort")
                        .HasFilter("is_discontinued = false AND is_published = true");

                    b.ToTable("cross_references", null, t =>
                        {
                            t.HasCheckConstraint("chk_xref_machine_type", "machine_type IS NULL OR machine_type IN ('agriculture', 'commercial', 'construction', 'industrial', 'others')");
                        });
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.DictEngine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EngineBrand")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("engine_brand");

                    b.Property<string>("EngineType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("engine_type");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_dict_engine");

                    b.HasIndex("DeletedAt", "SortOrder")
                        .HasDatabaseName("idx_dict_engine_active")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("EngineBrand", "EngineType")
                        .IsUnique()
                        .HasDatabaseName("ix_dict_engine_engine_brand_engine_type");

                    b.ToTable("dict_engine", (string)null);
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.DictMachine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("MachineBrand")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("machine_brand");

                    b.Property<string>("MachineCategory")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("others")
                        .HasColumnName("machine_category");

                    b.Property<string>("MachineModel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("machine_model");

                    b.Property<string>("MachineName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("machine_name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_dict_machine");

                    b.HasIndex("DeletedAt", "MachineCategory")
                        .HasDatabaseName("idx_dict_machine_category")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("DeletedAt", "SortOrder")
                        .HasDatabaseName("idx_dict_machine_active")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("MachineBrand", "MachineModel", "MachineName")
                        .IsUnique()
                        .HasDatabaseName("ix_dict_machine_machine_brand_machine_model_machine_name");

                    b.ToTable("dict_machine", (string)null);
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.DictMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("MediaModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("media_model");

                    b.Property<string>("MediaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("media_name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_dict_media");

                    b.HasIndex("DeletedAt", "SortOrder")
                        .HasDatabaseName("idx_dict_media_active")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("MediaName", "MediaModel")
                        .IsUnique()
                        .HasDatabaseName("ix_dict_media_media_name_media_model");

                    b.ToTable("dict_media", (string)null);
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.DictOemNo3", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("OemNo3")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("oem_no_3");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_dict_oem_no3");

                    b.HasIndex("OemNo3")
                        .IsUnique()
                        .HasDatabaseName("ix_dict_oem_no3_oem_no_3");

                    b.HasIndex("DeletedAt", "SortOrder")
                        .HasDatabaseName("idx_dict_oem_no3_active")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("SortOrder", "OemNo3")
                        .HasDatabaseName("idx_dict_oem_no3_sort")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("dict_oem_no3", (string)null);
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.DictProductName1", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ProductName1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name_1");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_dict_product_name1");

                    b.HasIndex("ProductName1")
                        .IsUnique()
                        .HasDatabaseName("ix_dict_product_name1_product_name_1");

                    b.HasIndex("DeletedAt", "SortOrder")
                        .HasDatabaseName("idx_dict_product_name1_active")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("dict_product_name1", (string)null);
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.DictProductName2", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ProductName2")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name_2");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_dict_product_name2");

                    b.HasIndex("ProductName2")
                        .IsUnique()
                        .HasDatabaseName("ix_dict_product_name2_product_name_2");

                    b.HasIndex("DeletedAt", "SortOrder")
                        .HasDatabaseName("idx_dict_product_name2_active")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("dict_product_name2", (string)null);
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.DictType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_dict_type");

                    b.HasIndex("Type")
                        .IsUnique()
                        .HasDatabaseName("ix_dict_type_type");

                    b.HasIndex("DeletedAt", "SortOrder")
                        .HasDatabaseName("idx_dict_type_active")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("dict_type", (string)null);
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.EtlProgressLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AlertSent")
                        .HasColumnType("boolean")
                        .HasColumnName("alert_sent");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<long?>("CheckpointId")
                        .HasColumnType("bigint")
                        .HasColumnName("checkpoint_id");

                    b.Property<double>("DurationSec")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_sec");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("entity_type");

                    b.Property<long>("ErrorCount")
                        .HasColumnType("bigint")
                        .HasColumnName("error_count");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("finished_at");

                    b.Property<long>("IndexPendingCount")
                        .HasColumnType("bigint")
                        .HasColumnName("index_pending_count");

                    b.Property<long>("IndexedCount")
                        .HasColumnType("bigint")
                        .HasColumnName("indexed_count");

                    b.Property<long>("InsertedCount")
                        .HasColumnType("bigint")
                        .HasColumnName("inserted_count");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mode");

                    b.Property<long>("ReadCount")
                        .HasColumnType("bigint")
                        .HasColumnName("read_count");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.Property<long>("SkippedCount")
                        .HasColumnType("bigint")
                        .HasColumnName("skipped_count");

                    b.Property<long>("SkippedDuplicate")
                        .HasColumnType("bigint")
                        .HasColumnName("skipped_duplicate");

                    b.Property<long>("SkippedMissingOem")
                        .HasColumnType("bigint")
                        .HasColumnName("skipped_missing_oem");

                    b.Property<long>("SkippedNullField")
                        .HasColumnType("bigint")
                        .HasColumnName("skipped_null_field");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<long>("UpdatedCount")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_count");

                    b.HasKey("Id")
                        .HasName("pk_etl_progress_log");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_etl_progress_log_status");

                    b.HasIndex("EntityType", "FinishedAt")
                        .HasDatabaseName("ix_etl_progress_log_entity_type_finished_at");

                    b.ToTable("etl_progress_log", (string)null);
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.LoginAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FailureReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip");

                    b.Property<DateTimeOffset>("LoginAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("login_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_agent");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_login_audit_logs");

                    b.HasIndex("LoginAt")
                        .HasDatabaseName("ix_login_audit_logs_login_at");

                    b.HasIndex("UserId", "LoginAt")
                        .HasDatabaseName("idx_login_audit_user_login_at");

                    b.ToTable("login_audit_logs", (string)null);
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.MachineApplication", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CabinType")
                        .HasColumnType("text")
                        .HasColumnName("cabin_type");

                    b.Property<string>("Capacity")
                        .HasColumnType("text")
                        .HasColumnName("capacity");

                    b.Property<string>("CarBodyType")
                        .HasColumnType("text")
                        .HasColumnName("car_body_type");

                    b.Property<string>("ChassisType")
                        .HasColumnType("text")
                        .HasColumnName("chassis_type");

                    b.Property<string>("Co2EmissionStandard")
                        .HasColumnType("text")
                        .HasColumnName("co2_emission_standard");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EngineBrand")
                        .HasColumnType("text")
                        .HasColumnName("engine_brand");

                    b.Property<string>("EngineDisplacement")
                        .HasColumnType("text")
                        .HasColumnName("engine_displacement");

                    b.Property<string>("EngineEnergy")
                        .HasColumnType("text")
                        .HasColumnName("engine_energy");

                    b.Property<string>("EngineModel")
                        .HasColumnType("text")
                        .HasColumnName("engine_model");

                    b.Property<string>("EngineSerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("engine_serial_number");

                    b.Property<string>("EngineType")
                        .HasColumnType("text")
                        .HasColumnName("engine_type");

                    b.Property<string>("GeographicArea")
                        .HasColumnType("text")
                        .HasColumnName("geographic_area");

                    b.Property<string>("Gvwr")
                        .HasColumnType("text")
                        .HasColumnName("gvwr");

                    b.Property<bool>("IsDiscontinued")
                        .HasColumnType("boolean")
                        .HasColumnName("is_discontinued");

                    b.Property<bool>("IsOngoing")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ongoing");

                    b.Property<string>("MachineBrand")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("machine_brand");

                    b.Property<string>("MachineCategory")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("others")
                        .HasColumnName("machine_category");

                    b.Property<string>("MachineModel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("machine_model");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<int?>("NumberOfCylinders")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_cylinders");

                    b.Property<string>("Power")
                        .HasColumnType("text")
                        .HasColumnName("power");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<DateTime?>("ProductionDateEnd")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("production_date_end");

                    b.Property<DateTime?>("ProductionDateStart")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("production_date_start");

                    b.Property<string>("SerialNumberFrom")
                        .HasColumnType("text")
                        .HasColumnName("serial_number_from");

                    b.Property<string>("SerialNumberTo")
                        .HasColumnType("text")
                        .HasColumnName("serial_number_to");

                    b.Property<string>("Series")
                        .HasColumnType("text")
                        .HasColumnName("series");

                    b.Property<string>("Tonnage")
                        .HasColumnType("text")
                        .HasColumnName("tonnage");

                    b.Property<string>("TransmissionType")
                        .HasColumnType("text")
                        .HasColumnName("transmission_type");

                    b.HasKey("Id")
                        .HasName("pk_machine_applications");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_machine_applications_product_id");

                    b.HasIndex("MachineBrand", "MachineModel")
                        .HasDatabaseName("ix_machine_applications_machine_brand_machine_model");

                    b.HasIndex("MachineCategory", "MachineBrand", "MachineModel")
                        .HasDatabaseName("idx_machine_apps_category");

                    b.ToTable("machine_applications", null, t =>
                        {
                            t.HasCheckConstraint("chk_machine_apps_category", "machine_category IS NULL OR machine_category IN ('agriculture', 'commercial', 'construction', 'industrial', 'others')");
                        });
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.Partition6Placeholder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_partition6_placeholder");

                    b.ToTable("partition6_placeholder", (string)null);
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("BypassPressure")
                        .HasColumnType("numeric")
                        .HasColumnName("bypass_pressure");

                    b.Property<decimal?>("BypassValveHr")
                        .HasColumnType("numeric")
                        .HasColumnName("bypass_valve_hr");

                    b.Property<decimal?>("BypassValveLr")
                        .HasColumnType("numeric")
                        .HasColumnName("bypass_valve_lr");

                    b.Property<decimal?>("CartonHeightMm")
                        .HasColumnType("numeric")
                        .HasColumnName("carton_height_mm");

                    b.Property<decimal?>("CartonLengthMm")
                        .HasColumnType("numeric")
                        .HasColumnName("carton_length_mm");

                    b.Property<decimal?>("CartonWidthMm")
                        .HasColumnType("numeric")
                        .HasColumnName("carton_width_mm");

                    b.Property<decimal?>("CollapsePressureBar")
                        .HasColumnType("numeric")
                        .HasColumnName("collapse_pressure_bar");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("D1Mm")
                        .HasColumnType("numeric")
                        .HasColumnName("d1_mm");

                    b.Property<string>("D1MmRaw")
                        .HasColumnType("text")
                        .HasColumnName("d1_mm_raw");

                    b.Property<decimal?>("D2Mm")
                        .HasColumnType("numeric")
                        .HasColumnName("d2_mm");

                    b.Property<string>("D2MmRaw")
                        .HasColumnType("text")
                        .HasColumnName("d2_mm_raw");

                    b.Property<decimal?>("D3Mm")
                        .HasColumnType("numeric")
                        .HasColumnName("d3_mm");

                    b.Property<string>("D3MmRaw")
                        .HasColumnType("text")
                        .HasColumnName("d3_mm_raw");

                    b.Property<decimal?>("D4Mm")
                        .HasColumnType("numeric")
                        .HasColumnName("d4_mm");

                    b.Property<string>("D4MmRaw")
                        .HasColumnType("text")
                        .HasColumnName("d4_mm_raw");

                    b.Property<string>("D7Thread")
                        .HasColumnType("text")
                        .HasColumnName("d7_thread");

                    b.Property<string>("D8Thread")
                        .HasColumnType("text")
                        .HasColumnName("d8_thread");

                    b.Property<DateTime?>("DiscontinuedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("discontinued_at");

                    b.Property<string>("Efficiency1")
                        .HasColumnType("text")
                        .HasColumnName("efficiency_1");

                    b.Property<string>("Efficiency2")
                        .HasColumnType("text")
                        .HasColumnName("efficiency_2");

                    b.Property<decimal?>("H1Mm")
                        .HasColumnType("numeric")
                        .HasColumnName("h1_mm");

                    b.Property<string>("H1MmRaw")
                        .HasColumnType("text")
                        .HasColumnName("h1_mm_raw");

                    b.Property<decimal?>("H2Mm")
                        .HasColumnType("numeric")
                        .HasColumnName("h2_mm");

                    b.Property<string>("H2MmRaw")
                        .HasColumnType("text")
                        .HasColumnName("h2_mm_raw");

                    b.Property<decimal?>("H3Mm")
                        .HasColumnType("numeric")
                        .HasColumnName("h3_mm");

                    b.Property<string>("H3MmRaw")
                        .HasColumnType("text")
                        .HasColumnName("h3_mm_raw");

                    b.Property<decimal?>("H4Mm")
                        .HasColumnType("numeric")
                        .HasColumnName("h4_mm");

                    b.Property<string>("H4MmRaw")
                        .HasColumnType("text")
                        .HasColumnName("h4_mm_raw");

                    b.Property<string>("ImageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_key");

                    b.Property<string>("ImageStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("image_status");

                    b.Property<bool>("IsDiscontinued")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_discontinued");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_published");

                    b.Property<decimal?>("MasterBoxHeightMm")
                        .HasColumnType("numeric")
                        .HasColumnName("master_box_height_mm");

                    b.Property<decimal?>("MasterBoxLengthMm")
                        .HasColumnType("numeric")
                        .HasColumnName("master_box_length_mm");

                    b.Property<int?>("MasterBoxQty")
                        .HasColumnType("integer")
                        .HasColumnName("master_box_qty");

                    b.Property<decimal?>("MasterBoxWeightKgs")
                        .HasColumnType("numeric")
                        .HasColumnName("master_box_weight_kgs");

                    b.Property<decimal?>("MasterBoxWidthMm")
                        .HasColumnType("numeric")
                        .HasColumnName("master_box_width_mm");

                    b.Property<string>("Media")
                        .HasColumnType("text")
                        .HasColumnName("media");

                    b.Property<string>("MediaModel")
                        .HasColumnType("text")
                        .HasColumnName("media_model");

                    b.Property<string>("Mr1")
                        .HasColumnType("text")
                        .HasColumnName("mr_1");

                    b.Property<int?>("NoBypassValves")
                        .HasColumnType("integer")
                        .HasColumnName("no_bypass_valves");

                    b.Property<int?>("NoCheckValves")
                        .HasColumnType("integer")
                        .HasColumnName("no_check_valves");

                    b.Property<string>("Oem2")
                        .HasColumnType("text")
                        .HasColumnName("oem_2");

                    b.Property<string>("OemNoDisplay")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("oem_no_display");

                    b.Property<string>("OemNoNormalized")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("oem_no_normalized");

                    b.Property<string>("ProductName1")
                        .HasColumnType("text")
                        .HasColumnName("product_name_1");

                    b.Property<string>("ProductName2")
                        .HasColumnType("text")
                        .HasColumnName("product_name_2");

                    b.Property<string>("ProductName3")
                        .HasColumnType("text")
                        .HasColumnName("product_name_3");

                    b.Property<int?>("QtyPerCarton")
                        .HasColumnType("integer")
                        .HasColumnName("qty_per_carton");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SealingMaterial")
                        .HasColumnType("text")
                        .HasColumnName("sealing_material");

                    b.Property<string>("TempRange")
                        .HasColumnType("text")
                        .HasColumnName("temp_range");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("VolumePerCartonM3")
                        .HasColumnType("numeric")
                        .HasColumnName("volume_per_carton_m3");

                    b.Property<decimal?>("WeightKgs")
                        .HasColumnType("numeric")
                        .HasColumnName("weight_kgs");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("D1Mm")
                        .HasDatabaseName("ix_products_d1_mm");

                    b.HasIndex("D2Mm")
                        .HasDatabaseName("ix_products_d2_mm");

                    b.HasIndex("H1Mm")
                        .HasDatabaseName("ix_products_h1_mm");

                    b.HasIndex("Mr1")
                        .IsUnique()
                        .HasDatabaseName("idx_products_mr_1_unique")
                        .HasFilter("mr_1 IS NOT NULL");

                    b.HasIndex("Oem2")
                        .HasDatabaseName("ix_products_oem_2");

                    b.HasIndex("OemNoDisplay")
                        .HasDatabaseName("ix_products_oem_no_display");

                    b.HasIndex("OemNoNormalized")
                        .HasDatabaseName("idx_products_oem_no_normalized")
                        .HasFilter("oem_no_normalized IS NOT NULL");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_products_type");

                    b.HasIndex("Type", "D1Mm")
                        .HasDatabaseName("idx_products_type_d1");

                    b.HasIndex("Type", "D2Mm")
                        .HasDatabaseName("idx_products_type_d2");

                    b.HasIndex("Type", "H1Mm")
                        .HasDatabaseName("idx_products_type_h1");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("chk_mr_1_format", "mr_1 IS NULL OR mr_1 ~ '^[A-Za-z0-9]{1,10}$'");
                        });
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.ProductHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("change_type");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("changed_by");

                    b.Property<string>("ChangedFields")
                        .HasColumnType("jsonb")
                        .HasColumnName("changed_fields");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_product_history");

                    b.HasIndex("ProductId", "ChangedAt")
                        .HasDatabaseName("ix_product_history_product_id_changed_at");

                    b.ToTable("product_history", (string)null);
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.ProductImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("content_type");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("ImageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_key");

                    b.Property<string>("ImageRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("detail")
                        .HasColumnName("image_role");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("OemNo3")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("oem_no_3");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<short>("Slot")
                        .HasColumnType("smallint")
                        .HasColumnName("slot");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("uploaded_by");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_product_images");

                    b.HasIndex("OemNo3")
                        .IsUnique()
                        .HasDatabaseName("uq_product_images_primary")
                        .HasFilter("image_role = 'primary' AND oem_no_3 IS NOT NULL");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_images_product_id");

                    b.HasIndex("ProductId", "Slot")
                        .IsUnique()
                        .HasDatabaseName("uq_product_images_detail_slot")
                        .HasFilter("image_role = 'detail'");

                    b.ToTable("product_images", null, t =>
                        {
                            t.HasCheckConstraint("chk_image_role", "image_role IN ('primary', 'detail')");

                            t.HasCheckConstraint("chk_image_role_slot", "(image_role = 'primary' AND slot = 1) OR (image_role = 'detail' AND slot BETWEEN 2 AND 6)");
                        });
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("created_ip");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long?>("ReplacedByTokenId")
                        .HasColumnType("bigint")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.SearchIndexDeadLetter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastRecoveryAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_recovery_at");

                    b.Property<string>("LastRecoveryError")
                        .HasColumnType("text")
                        .HasColumnName("last_recovery_error");

                    b.Property<DateTime>("MovedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("moved_at");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operation");

                    b.Property<long>("OriginalId")
                        .HasColumnType("bigint")
                        .HasColumnName("original_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("RecoveredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("recovered_at");

                    b.Property<long?>("RecoveredToPendingId")
                        .HasColumnType("bigint")
                        .HasColumnName("recovered_to_pending_id");

                    b.Property<int>("RecoveryCount")
                        .HasColumnType("integer")
                        .HasColumnName("recovery_count");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_search_index_dead_letter");

                    b.HasIndex("MovedAt")
                        .HasDatabaseName("ix_search_index_dead_letter_moved_at");

                    b.HasIndex("Operation")
                        .HasDatabaseName("ix_search_index_dead_letter_operation");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_search_index_dead_letter_status");

                    b.HasIndex("Status", "RecoveryCount", "LastRecoveryAt")
                        .HasDatabaseName("idx_dead_letter_active_recovery")
                        .HasFilter("status = 'active'");

                    b.ToTable("search_index_dead_letter", (string)null);
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.SearchIndexPending", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime>("NextRetryAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operation");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.HasKey("Id")
                        .HasName("pk_search_index_pending");

                    b.HasIndex("NextRetryAt", "RetryCount")
                        .HasDatabaseName("idx_pending_retry");

                    b.ToTable("search_index_pending", (string)null);
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.SecurityEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<JsonDocument>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_agent");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_security_events");

                    b.ToTable("security_events", (string)null);
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_system_settings");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_count");

                    b.Property<string>("FullName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastLoginIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("last_login_ip");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("viewer")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("idx_users_deleted_at")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.XrefOemBrand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_xref_oem_brand");

                    b.HasIndex("Brand")
                        .IsUnique()
                        .HasDatabaseName("ix_xref_oem_brand_brand");

                    b.HasIndex("DeletedAt", "SortOrder")
                        .HasDatabaseName("idx_xref_oem_brand_active")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("xref_oem_brand", (string)null);
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.CrossReference", b =>
                {
                    b.HasOne("SakuraFilter.Core.Entities.Product", "Product")
                        .WithMany("CrossReferences")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cross_references_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.MachineApplication", b =>
                {
                    b.HasOne("SakuraFilter.Core.Entities.Product", null)
                        .WithMany("MachineApplications")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_machine_applications_products_product_id");
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.ProductImage", b =>
                {
                    b.HasOne("SakuraFilter.Core.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_images_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("SakuraFilter.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SakuraFilter.Core.Entities.Product", b =>
                {
                    b.Navigation("CrossReferences");

                    b.Navigation("Images");

                    b.Navigation("MachineApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
