# Internal runner: backend (auto-generated by dev-up.ps1)
$ErrorActionPreference = 'Continue'
Set-Location 'D:\projects\sakurafilter\backend\src\SakuraFilter.Api'
Write-Host '[Backend] Port 5148 starting...' -ForegroundColor Yellow
dotnet run -c Release --no-build --launch-profile http 2>&1 | ForEach-Object { Write-Host $_ }
Write-Host ''
Write-Host '[Backend] exited, press Enter to close window ...' -ForegroundColor DarkGray
Read-Host | Out-Null