# Internal runner: frontend (auto-generated by dev-up.ps1)
$ErrorActionPreference = 'Continue'
Set-Location 'D:\projects\sakurafilter\frontend'
Write-Host '[Frontend] Port 5175 starting...' -ForegroundColor Yellow
npm run dev 2>&1 | ForEach-Object { Write-Host $_ }
Write-Host ''
Write-Host '[Frontend] exited, press Enter to close window ...' -ForegroundColor DarkGray
Read-Host | Out-Null