# SakuraFilter 一键启动脚本 (Windows / PowerShell 5+)
# 作用: 加载 .env 注入环境变量, 后端 + 前端分别开新窗口后台运行
# 用法 (项目根目录):
#   powershell -ExecutionPolicy Bypass -File .\scripts\dev-up.ps1                  # 默认端口 (后端 5148, 前端 5175)
#   powershell -ExecutionPolicy Bypass -File .\scripts\dev-up.ps1 -FrontendPort 5180
#   powershell -ExecutionPolicy Bypass -File .\scripts\dev-up.ps1 -BackendPort 5150
#   powershell -ExecutionPolicy Bypass -File .\scripts\dev-up.ps1 -SkipBackend     # 只启动前端
#   powershell -ExecutionPolicy Bypass -File .\scripts\dev-up.ps1 -SkipFrontend    # 只启动后端
[CmdletBinding()]
param(
    [int]$BackendPort = 5148,
    [int]$FrontendPort = 5175,
    [switch]$SkipBackend,
    [switch]$SkipFrontend,
    [switch]$Rebuild
)

$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
Set-Location $root

# 复用的 UTF-8 无 BOM 编码 (PS5 不支持 utf8NoBOM, 用 BCL API)
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

# ===== 1. 加载 .env =====
$envFile = Join-Path $root '.env'
if (-not (Test-Path $envFile)) {
    Write-Host "[ERROR] .env not found: $envFile" -ForegroundColor Red
    exit 1
}
Write-Host "[1/4] Loading .env ..." -ForegroundColor Cyan
Get-Content $envFile | ForEach-Object {
    $line = $_.Trim()
    if ($line -eq '' -or $line.StartsWith('#')) { return }
    $eqIdx = $line.IndexOf('=')
    if ($eqIdx -le 0) { return }
    $key = $line.Substring(0, $eqIdx).Trim()
    $val = $line.Substring($eqIdx + 1).Trim()
    if ($val -match '^"(.+)"$') { $val = $Matches[1] }
    [System.Environment]::SetEnvironmentVariable($key, $val, 'Process')
}

# 强制覆盖端口
[System.Environment]::SetEnvironmentVariable('ASPNETCORE_URLS', "http://localhost:$BackendPort", 'Process')
Write-Host "  Backend URL  = http://localhost:$BackendPort" -ForegroundColor Gray
Write-Host "  Frontend URL = http://localhost:$FrontendPort" -ForegroundColor Gray

# ===== 2. (可选) 后端 Release 重新编译 =====
$backendDir = Join-Path $root 'backend\src\SakuraFilter.Api'
if ($Rebuild -and -not $SkipBackend) {
    Write-Host "[2/4] Rebuilding backend (Release) ..." -ForegroundColor Cyan
    Push-Location $backendDir
    try {
        Get-Process -Name 'SakuraFilter.Api' -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
        dotnet build -c Release --nologo
        if ($LASTEXITCODE -ne 0) { throw "dotnet build failed" }
    } finally {
        Pop-Location
    }
} else {
    Write-Host "[2/4] Skipping rebuild (use -Rebuild to enable)" -ForegroundColor DarkGray
}

# ===== 3. 启动后端 =====
$backendRunner = Join-Path $root 'scripts\_run-backend.ps1'
$backendRunnerContent = @"
# Internal runner: backend (auto-generated by dev-up.ps1)
`$ErrorActionPreference = 'Continue'
Set-Location '$backendDir'
Write-Host '[Backend] Port $BackendPort starting...' -ForegroundColor Yellow
dotnet run -c Release --no-build --launch-profile http 2>&1 | ForEach-Object { Write-Host `$_ }
Write-Host ''
Write-Host '[Backend] exited, press Enter to close window ...' -ForegroundColor DarkGray
Read-Host | Out-Null
"@
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($backendRunner, $backendRunnerContent, $utf8NoBom)

if (-not $SkipBackend) {
    Write-Host "[3/4] Starting backend (new window)..." -ForegroundColor Cyan
    Start-Process -FilePath 'powershell.exe' `
        -ArgumentList @('-NoLogo', '-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $backendRunner) `
        -WorkingDirectory $backendDir `
        -WindowStyle Normal
}

# ===== 4. 启动前端 (临时改 vite.config.ts port) =====
$frontendRunner = Join-Path $root 'scripts\_run-frontend.ps1'
$frontendDir = Join-Path $root 'frontend'
$viteConfig = Join-Path $frontendDir 'vite.config.ts'
$configOriginal = Get-Content $viteConfig -Raw
# 用 'port' 单引号 + '$1' 防止 PS 插值 (避免 `port` 被当成变量)
$configPatched = [regex]::Replace($configOriginal, "(?ms)(port:\s*)\d+", '${1}' + $FrontendPort, 1)
if ($configPatched -ne $configOriginal) {
    # 写文件保持无 BOM UTF-8 (PS5 utf8NoBOM 不支持, 用 BCL API)
    [System.IO.File]::WriteAllText($viteConfig, $configPatched, $utf8NoBom)
    Write-Host "  (vite.config.ts port -> $FrontendPort)" -ForegroundColor DarkGray
} elseif ($configOriginal -match "(?ms)port:\s*$FrontendPort\b") {
    Write-Host "  (vite.config.ts port already = $FrontendPort)" -ForegroundColor DarkGray
} else {
    Write-Host "  [WARN] no port: NNN found in vite.config.ts, frontend will use 5173" -ForegroundColor Yellow
}

$frontendRunnerContent = @"
# Internal runner: frontend (auto-generated by dev-up.ps1)
`$ErrorActionPreference = 'Continue'
Set-Location '$frontendDir'
Write-Host '[Frontend] Port $FrontendPort starting...' -ForegroundColor Yellow
npm run dev 2>&1 | ForEach-Object { Write-Host `$_ }
Write-Host ''
Write-Host '[Frontend] exited, press Enter to close window ...' -ForegroundColor DarkGray
Read-Host | Out-Null
"@
[System.IO.File]::WriteAllText($frontendRunner, $frontendRunnerContent, $utf8NoBom)

if (-not $SkipFrontend) {
    Write-Host "[4/4] Starting frontend (new window)..." -ForegroundColor Cyan
    Start-Process -FilePath 'powershell.exe' `
        -ArgumentList @('-NoLogo', '-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $frontendRunner) `
        -WorkingDirectory $frontendDir `
        -WindowStyle Normal
}

# ===== 5. 等待并检查端口 =====
Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "  SakuraFilter startup commands sent" -ForegroundColor Green
Write-Host "  Backend  http://localhost:$BackendPort" -ForegroundColor Green
Write-Host "  Frontend http://localhost:$FrontendPort" -ForegroundColor Green
Write-Host "  Admin    admin / Admin@2026" -ForegroundColor Green
Write-Host "  Operator operator / Operator@2026" -ForegroundColor Green
Write-Host "  Stop:    scripts\dev-down.ps1" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green

Write-Host ""
Write-Host "Wait 8s, checking ports..." -ForegroundColor Cyan
Start-Sleep -Seconds 8
foreach ($port in @($BackendPort, $FrontendPort)) {
    $conn = netstat -ano | Select-String ":$port\s" | Select-Object -First 1
    if ($conn -and $conn -match '\s(\d+)$') {
        Write-Host "  [OK]   :$port  (PID $($Matches[1]))" -ForegroundColor Green
    } else {
        Write-Host "  [WAIT] :$port  not ready yet (check the new window log)" -ForegroundColor Yellow
    }
}
